# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ccd81df1da06ce3e1bbb2eac8906045264b87f0509a75785e4e05bfac1a1d82c17994088d28d067a5ca3be71bd7089f9cdfb5683d15839dbb5b6ac5d6c3982

test:
  secret_key_base: b3c2cb31513894a43183c9e623d6633ddbf213a5013f2b60b5446e8dd361dbeaf5014025e7077c18661200abd069fff51f234f805747f9e55adf44f793eb54a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
