---
- :student_name: asdsalsjj
  :owl_name: akjdjhl
  :year_born: 2010-03
  :favorite_spell: asdkla
  :house: Slitherand
- :student_name: asdsalkj
  :owl_name: alkjdkas
  :year_born: 2012-10
  :favorite_spell: asd
  :house: Hufflepuff
