#!/usr/bin/env ruby 

require 'httparty'
require 'active_record'
require 'json'

if ARGV.length == 1 
	if ARGV.last == "--get"
		HTTParty.get "http://127.0.0.1:4567/api" 
	else 
		abort "USAGE: method [id] [name] [description]"
	end 
elsif ARGV.length == 2 
	method, id = ARGV
	if method == "--delete"
		HTTParty.delete "http://127.0.0.1:4567/breeds/#{id}"
	else 
		abort "USAGE: method [id] [name] [description]"
	end 
elsif ARGV.length == 4 
	method, id, name, description = ARGV 
	if method == "--put"
		HTTParty.put(
			"http://127.0.0.1:4567/breeds/#{id}", 
			{
			 :body => 
				{
				       "name" => name,
				"description" => description
				}
			}
		)
	else 
		abort "USAGE: method [id] [name] [description]"
	end  
end 

