#!/usr/bin/env ruby 

require 'httparty'
require 'active_record'
require 'json'

if ARGV.length == 1 
	if ARGV.last == "--get"
		JSON.load(HTTParty.get("http://127.0.0.1:4567/api")).each do |breed|
			puts breed["id"], breed["name"], breed["description"]
		end  
	else 
		abort "USAGE: method [id] [name] [description]"
	end 
elsif ARGV.length == 2 
	method, id = ARGV
	if method == "--delete"
		JSON.load(HTTParty.delete("http://127.0.0.1:4567/api", {body: {id: id}})).each do |breed|
			puts breed["id"], breed["name"], breed["description"]
		end  
	else 
		abort "USAGE: method [id] [name] [description]"
	end 
elsif ARGV.length == 3 
	method, name, description = ARGV 
	if method == "--post"
		JSON.load(HTTParty.post(
			"http://127.0.0.1:4567/api", 
			{
			 :body => 
				{
				       :name => name,
				:description => description
				}
			}
		)).each do |breed|
			puts breed["id"], breed["name"], breed["description"]
		end   
	else 
		abort "USAGE: method [id] [name] [description]"
	end
else 
	abort "USAGE: method [id] [name] [description]"
end 

