development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: db
  pool: 5
  username: shotaro
  password: testuser
test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: db
  pool: 5
  username: shotaro
  password: testuser