# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0447623a29c73a773d8556d4ae5e8e1d001b4fc6e28b4c0a506f5cfb4b1d0499a045cb69a6b5cce6920d30a0d55ef832046c92b1204ae243f53a1b804782e8b5

test:
  secret_key_base: 12cd33742e9b55fdc4194aa8370d35eecc2c001519665fe77d398c499bcc155eb3594af2734324f78acee339d8ca6b195c6c6066bf3d041e43de8dfd14fba9ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
