# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ce1c11d3278ac18197cbc65018555f494696c5233ddfa63d89b35f4f1142afd0805520388ddad381ba22d3ee373c6324581f304dd078d12f542f282c420ddcb

test:
  secret_key_base: a26affbdae48efc8f1f29280bbcc2e7b8e413bdcc082a1029d86f249295e40b2f91a4b44553ce6a69c4a424dbc06ee1a2437393137e05113f0fa4197f237a550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
