# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 667d7b1feade1735e1ceb7102c6f98ec1ba606de6d8eaa8ad83e0000a56be4a2a9c0069a6c501d2d95c4601f51f116aa925eea0c38c33a553bd081c87a8082ca

test:
  secret_key_base: 8aa2f1cb0b4d9e70c1beb1677e8835e1c9f4df98488fcc71ea3013276cbf6866c1f8c1d5ba7b3c8a71daef6604ca07b9bee896beade8b2ee50bd944d8a1e451a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
